username=input("Имя пользователя ")
print(username)
title=input("Заголовок заметки ")
title_1=input("Подзаголовок 1 ")
title_2=input("Подзаголовок 2 ")
title_3=input("Подзаголовок 3 ")
title_=[title_1,title_2,title_3]
print(title)
print(title_)
content=input("Описание заметки ")
print(content)
status=input("Статус заметки ")
print(status)
created_date=input("Дата создания заметки:день-месяц-год ")
print(created_date[:5])
issue_date=input("Дата истечения заметки:день-месяц-год ")
print(issue_date[:5])