username=("Имя пользователя")
print(username)
title=("Заголовок заметки")
print(title)
content=("Описание заметки")
print(content)
status=("Статус заметки")
print(status)
created_date=("Дата создания заметки:15-12-2024")
print(created_date)
issue_date=("Дата истечения заметки:15-01-2025")
print(issue_date)